
name: build garrysmod

on:
  workflow_dispatch :
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - main
    tags: [ 'v*.*.*' ]
jobs:
  push:
    name: "garrysmod"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/Equoo/garrysmod
